# Generated by Django 3.0.4 on 2020-03-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sub',
            name='subSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Size'),
        ),
    ]
