# Generated by Django 3.0.4 on 2020-04-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='item',
            new_name='items',
        ),
    ]
