# Generated by Django 3.0.4 on 2020-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200405_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity2',
            name='comments',
            field=models.CharField(default='', max_length=100),
        ),
    ]
