# Generated by Django 3.0.4 on 2020-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_shoppingcart2_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart2',
            name='count',
        ),
    ]
