# Generated by Django 3.0.4 on 2020-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_shoppingcart2_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart2',
            name='status',
            field=models.CharField(default='Active', max_length=64),
        ),
    ]
